[default.extend-words]
# Base58 Solana addresses contain letter combinations that look like typos
iFo = "iFo"
Fo = "Fo"

[default.extend-identifiers]
# Ignore Solana public keys (base58 encoded)
ign1zuR3YsvLVsEu8WzsyazBA8EVWUxPPHKnhqhoSTB = "ign1zuR3YsvLVsEu8WzsyazBA8EVWUxPPHKnhqhoSTB"
iFoGoY5nMWpuMJogR7xjUAWDJtygHDF17zREeP4MKuD = "iFoGoY5nMWpuMJogR7xjUAWDJtygHDF17zREeP4MKuD"
SP1s4uFeTAX9jsXXmwyDs1gxYYf7cdDZ8qHUHVxE1yr = "SP1s4uFeTAX9jsXXmwyDs1gxYYf7cdDZ8qHUHVxE1yr"
DPoo15wWDqpPJJtS2MUZ49aRxqz5ZaaJCJP4z8bLuib = "DPoo15wWDqpPJJtS2MUZ49aRxqz5ZaaJCJP4z8bLuib"

[files]
extend-exclude = [
    "*.lock",
    "target/",
    "node_modules/",
    "dist/",
]
